openapi: 3.0.0
info:
  description: This API provides event stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: tpham100@my.bcit.ca

paths:
  /stats:
    get:
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets Check In and Booking Confirm processsed statistics
      responses:
        "200":
          description: Successfully returned a list of check in or booking confirm events
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/ReadingStats"
        "400":
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /health:
    get:
      tags:
        - admins
      summary: Gets the event health
      operationId: app.get_health
      description: Gets status of service is running or offline
      responses:
        "200":
          description: Service is running
        "400":
          description: Service is down
components:
  schemas:
    ReadingStats:
      required:
        - num_ci_readings
        - max_numPeople
        - num_bc_readings
        - max_numNights
      properties:
        num_ci_readings:
          type: integer
          example: 500000
        max_numPeople:
          type: integer
          example: 200
        num_bc_readings:
          type: integer
          example: 500000
        max_numNights:
          type: integer
          example: 250
      type: object
